### ISSUE TITLE
Diverse Wünsche und Vorschläge

### ISSUE THREAD

**Issue by MMeinhardt1** [minukodu/minuvis-webapp.iobroker#15]
Hallo Sepp,

hier mal ein paar Wünsche und Vorschläge von mir.

Wie auf dem Screenshot zu sehen, würde ich ein Überschriften-Widget ganz gut finden, so liesse sich das ganze optisch besser unterteilen.

![Ueberschrift_klein](https://user-images.githubusercontent.com/56205459/90769972-62c08000-e2f1-11ea-94e0-b458d8ba3e37.png)

Bei Verwendung des "Compact-Widgets" lässt sich ein Titel oder ähnliches eintragen, dieser taucht aber nirgends wieder auf. Schön wäre da eine Beschriftungsmöglichkeit wie auf dem Screenshot zu sehen, da dass rechte Feld auf dem Handy zu klein ist um alles einzutragen.

![Beschriftung_klein](https://user-images.githubusercontent.com/56205459/90769981-681dca80-e2f1-11ea-98f2-27dec2f1ad07.png)

Wünschen würde ich mir zusätzlich,
- Indicator-Widget, min. 2 Datenpunkte zur Auswertung und dann auch hinterlegbar verschiedene Icons, für z.B. eine Fenster- oder Türüberwachung
- Widget zur Batterieüberwachung mit unterschiedlichen Icons für "voll", "halbvoll" und "fast leer" oder so ähnlich je nach % der Batterie
- Widget zur Darstellung von z.B. Xiaomi Multisensoren für Temperatur, Luftfeuchtigkeit und Luftdruck wenn vorhanden, dann bräuchte man den "Compact-Mode" nicht verwenden um es in einer Darstellung zu haben

Ich glaube das war es vorerst von meiner Seite, sollte mir noch etwas einfallen kommt es hintendran.

Danke für die tolle Arbeit!

Gruß Michael

**Comment by MMeinhardt1** [comment]
Hallo Sepp,

die Änderungen in V1.5.0 klingen sehr gut und interessant, super Arbeit! Hast Du eine Idee wann Du das in den Minuvis Adapter integrieren wirst?

**Comment by SVallant** [comment]
Wenn alles klappt morgen oder übermorgen 😎

**Comment by SVallant** [comment]
Adapter V0.0.9 verfügbar !!!! ;-)

**Comment by MMeinhardt1** [comment]
Hallo Sepp,

vorhin installiert und schon ein paar Dinge "umgebaut", macht einen sehr sehr guten Eindruck! Danke für Deine tolle und aufopferungsvolle Arbeit. Ich hoffe Du hast bei dem ganzen auch einen persönlichen Vorteil. 

Gruß und schönen Restsonntag noch.
