### ISSUE TITLE
Indicatorwidget mit Zeitstempel

### ISSUE THREAD

**Issue by MMeinhardt1** [minukodu/minuvis-webapp.iobroker#17]
Hallo,

wenn ich da richtig erkannt habe steht bei jedem Widget das nicht in einem Compactwidget eingepackt ist, der letzte Zeitstempel. Lässt sich die tolle Funktion auch auf die Widgets umsetzen die in einem Compactwidget eingepackt sind, für jedes Widget einzeln. Eventuell auch auswählbar mit einer checkbox, anzeigen ja/nein. 

Danke

**Comment by SVallant** [comment]
closest fixed/not applicable in Version 2 of minuvis
