### ISSUE TITLE
Mac Safari issue on Mac OS Catalina 10.15.4

### ISSUE THREAD

**Issue by tempo3** [minukodu/minuvis-webapp.iobroker#2]
Blank page on Safari browser, no content presented. Same issue also on iPhone, iPad etc. Tested with minuvis Version 1.0.0 running on debian 10.3,
Chrome browser (current version) on Mac works fine.

**Comment by SVallant** [comment]
Have an output of the browser console ?

**Comment by tempo3** [comment]
ok, in Safari, the development mode has to be set up to enable the not signed 3rd party extension to allow. now its working on mac os. iPhone still open.

**Comment by tempo3** [comment]
Hello minukodu-Team,
The vis and the builder are great (only the problem with the apple mobiles...). After implementation of several devices, I've some ideas for improvement. It would be great to get these developments. First The my remarks to the Indicator and ValueSwitcher Widget:
-
The Indicator Widget is great. But the widget only knows two states (true / false). It would be better and more flexible if the number of states (like ValueSwitcher) could be specified and a value expected (e.g. 0/1/2 ...) as well as a color, a description and a symbol  and for each state. Example Homematic Window Rotary Handle: Status is open, closed or tilted ... Example LOW_BAT_ALARM value is 0/1/2 ... e. g. acknowledged

In general, it would be super, if other symbols can be used e. g. materialdesignicons.com. The icons are very limited.

ValueSwitcher Widget: It wold be great to have the possibility to describe the value and not only to show the value (e. g. Roller shutters open/closed/partial open).

Again, thanks  a lot for the vis! Great job!

**Comment by SVallant** [comment]
@tempo3 Thank you, nice to read this.
Our Roadmap looks like this at the moment:

1. create ioBroker-Adapter for minuvis [Link](https://github.com/minukodu/ioBroker.minuvis)
2. create Android-App for minuVis

of crouse minor changes are always possible, we have a lot of ideas for ourselves like a colorpicker-Widget, or a widget for the timeswitch-Adapter.
I will create 2 new issues to handle your feature-requests.

We also try to setup a dvelopment-environment for Apple-Devices.

Be patient ;-)

**Comment by SVallant** [comment]
We have tested on iPhones, but we could not reproduce the failure.
We fixed the "add to Startscreen"-Issue in the development-version.
Please test this Link in your devices an provide more information:
http://dev.builder.minukodu.de/minuvis/app/?url=http%3A%2F%2F94.130.57.38%3A9090&file=demo_READONLY.json&forceUpdate

Thank you

**Comment by SVallant** [comment]
autamtically close, no events ;-)
