### ISSUE TITLE
“json-Widget”, machbar?

### ISSUE THREAD

**Issue by MMeinhardt1** [minukodu/minuvis-webapp.iobroker#22]
Hallo Sepp,

besteht die Möglichkeit das Du ein konfigurierbares Widget für json Strings “bastelst”?
Use-Case bei mir, ich nutze den tollen SmartControl Adapter und dieser schreibt Einträge als json in einen Datenpunkt und so könnte man sich die “Schaltvorgänge” in MinuVis anzeigen lassen. Der LogParser Adapter bietet solche json Strings auch an.

Oder gibt es da ne andere Möglichkeit?

Danke

**Comment by SVallant** [comment]
Wie sieht das json aus?
hast du ein Beispiel ?
Ich habe den Adapter mal installiert. Wo finde ich das json ?

**Comment by MMeinhardt1** [comment]
Hallo Sepp,

hier ist der Beitrag aus dem Forum, https://forum.iobroker.net/topic/36750/test-adapter-smartcontrol-0-3-x-latest/121 dort steht der Datenpunkt. 
Ich hoffe das hilft erstmal. 

Danke

**Comment by SVallant** [comment]
workaround:
http://dev.builder.minukodu.de/minuvis/app/?url=http%3A%2F%2F94.130.57.38%3A9090%2F&file=LogTest.json&forceUpdate
Vis als iframe eingebunden ...

**Comment by SVallant** [comment]
http://dev.builder.minukodu.de/minuvis/app/?url=http%3A%2F%2F94.130.57.38%3A9090%2F&file=LogTest.json&forceUpdate

Widget "jsontable", erstmal ganz einfach ...

**Comment by MMeinhardt1** [comment]
Hi Sepp,

das ist ja der Knaller 😳
Ich komme leider erst morgen dazu es mir anzuschauen. 
Weltklasse!

**Comment by MMeinhardt1** [comment]
Hi Sepp,

ich habe das anpassbare json-Widget im dev getestet, macht nen guten Eindruck. Wann kommt die V1.7.0 in den Minuvis Adapter?

Danke für all Deine Arbeit und Mühen!

**Comment by SVallant** [comment]
ab V1.8 auch mit Möglichkeit der Titelspaltenänderung (Text udn Grösse)
