### ISSUE TITLE
“Slider” anpassen

### ISSUE THREAD

**Issue by MMeinhardt1** [minukodu/minuvis-webapp.iobroker#25]
Hi Sepp,
ich nutze den Slider für meine Rollläden und würde dazu gerne wissen ob es machbar wäre das dieser seinen Wert erst übergibt wenn man fertig mit dem “sliden” ist?

Danke

**Comment by SVallant** [comment]
Moin,
eigentlcih habe ich nur das onChange-Event
https://onsen.io/v2/api/react/Range.html
aber ich spiele shon seit längerem mit der Idee, einen anderen Slider einzusetzen.
ich guck mir das mlr an

Sepp

**Comment by MMeinhardt1** [comment]
Moin,
das klingt nicht schlecht, vielleicht findest Du ja etwas 😁

**Comment by SVallant** [comment]
Moin, kannst du das mal testen ?
http://dev.builder.minukodu.de/minuvis/app/?url=http%3A%2F%2F94.130.57.38%3A9090%2F&file=testRangeAndColor.json&forceUpdate
Im Builder range statt slider verwenden, hat Option "Update bei complete"
http://dev.builder.minukodu.de/  + Browser-Reload ;-)

**Comment by MMeinhardt1** [comment]
Hi Sepp,
das sieht sehr gut aus und ist zum steuern der Rollläden bestens geeignet! DANKE

**Comment by SVallant** [comment]
Ok, passt das vom Design auch  ?
Wenn ja mach ich nächste Woche das Adapter-Update

**Comment by MMeinhardt1** [comment]
Hi, vom Design her passt das auch soweit.
Was mir jetzt eben noch aufgefallen ist, die Checkbox vorne hat scheinbar keine Auswirkungen. Die Rollläden fahren erst beim loslassen, egal ob die Checkbox aktiviert oder deaktiviert ist.

**Comment by SVallant** [comment]
New Widget "range" = advanced slider
