### ISSUE TITLE
Wrong position of widget "linkbutton"

### ISSUE THREAD

**Issue by bauerpower69** [minukodu/minuvis-webapp.iobroker#30]
Hi,

it seems to me there is something wrong with the position of the widget:

**Position in Builder:**
![image](https://user-images.githubusercontent.com/25681982/103181466-85673480-48a1-11eb-8ce0-c30a29c54887.png)

**Position in App:**
![image](https://user-images.githubusercontent.com/25681982/103181472-9dd74f00-48a1-11eb-95ed-d16c4f4cf746.png)

Happy to help 

Joerg

**Comment by bauerpower69** [comment]
OK, it seems this widget is not (yet) part of the CompactMode....

**Comment by SVallant** [comment]
yes, you are right
linkbutton is at the moment not useable for compact mode

**Comment by bauerpower69** [comment]
Thank you taking care :-)

Yours 

Joerg

**Comment by SVallant** [comment]
closest fixed/not applicable in Version 2 of minuvis
