### ISSUE TITLE
(2107) <==Disconnect system.user.admin from ::ffff:192.168.xxxxx minukodu.0

### ISSUE THREAD

**Issue by iob2020** [minukodu/minuvis-webapp.iobroker#41]
In Version 1.13.0 
from time to time the app crashes / stopps (white screen) and I get the error message

(2107) <==Disconnect system.user.admin from ::ffff:192.168.26.100 minukodu.0

when i start a special side from the app. other sides work well.

Maybe it has something to do with the DP in iobroker, when they have missing values.
I think it only happens, when there are objects on the side, with missing values..

**Comment by SVallant** [comment]
solved in Version 2
try it here: http://v2.builder.minukodu.de/
Adapter 2.0 follows soon
release candidate 2: https://github.com/minukodu/ioBroker.minuvis/tree/V200rc2
forum: https://forum.iobroker.net/topic/43114/test-adapter-minuvis-2-x/

**Comment by SVallant** [comment]
solved in Version 2
