### ISSUE TITLE
Value (of ValueSwitcher/Slider) has wrong datatype

### ISSUE THREAD

**Issue by dev-xaur** [minukodu/minuvis-webapp.iobroker#7]
I was playing around a bit and came across the following problem. Both the slider and ValueSwitcher always send the value as a string.But my Shelly Switch expects a number, so the following message appears in the iobroker log:
`shelly.0 | 2020-05-08 22:31:30.127 | error | (29284) Datatype for SHSW-21#5A4267#1.Shutter.Position differs from expected, ignore state change! Please write correct datatype (number)`

the right event to go with it:
`stateChange | shelly.0.SHSW-21#5A4267#1.shutter.position | "30" | false | socketio.1 | 2020-05-08 22:31:30.124 | 2020-05-08 22:31:30.124`

**Comment by SVallant** [comment]
- Part 1: Builder now adds type of state to config: https://github.com/minukodu/minuvis-builder.iobroker/releases/tag/V1.0.4

- Part 2: App ... work ongoing ;-)

**Comment by dev-xaur** [comment]
hi, boths work fine in 1.0.4-dev
