### ISSUE TITLE
blank page if widget has no valid state

### ISSUE THREAD

**Issue by dev-xaur** [minukodu/minuvis-webapp.iobroker#9]
when adding a widget to a page (not a startpage) and don't select a state, it will stay blank.

Traceable by clicking on "blank" under 
http://builder.minukodu.de/minukodu/?url=http%3A%2F%2F94.130.57.38%3A9090%2F&file=dev-xaur.json&forceUpdate

**Comment by SVallant** [comment]
closest fixed in Version 2 of minuvis
